gui:
    screenMode: 'normal'
    language: en
    nerdFontsVersion: '3'
    showFileIcons: true # 在文件视图中隐藏文件图标
    theme:
        activeBorderColor:
            - '#ed8796'
            - bold
        inactiveBorderColor:
            - '#a5adcb'
        optionsTextColor:
            - '#8aadf4'
        selectedLineBgColor:
            - '#363a4f'
        cherryPickedCommitBgColor:
            - '#494d64'
        cherryPickedCommitFgColor:
            - '#ed8796'
        unstagedChangesColor:
            - '#ed8796'
        defaultFgColor:
            - '#cad3f5'
        searchingActiveBorderColor:
            - '#eed49f'
